### ISSUE TITLE
Parsing output error

### ISSUE THREAD

**Issue by andre-cloud** [JacksonBurns/py2sambvca#31]
Hello, 

I was running the following code with the last (version 1.3.3 from pip): 

```python
for i in files:
    nhc_p2s = p2s(
        os.path.join(os.getcwd(), i.split('.')[0], i),
        sphere_center_atom_ids = [65],
        z_ax_atom_ids = [65, 64],
        xz_plane_atoms_ids = [15, 64, 65, 82],
        path_to_sambvcax ="/Users/andrea/Sambvca21/sambvca21.x",
        sphere_radius = 7.5,
        working_dir = os.path.join(os.getcwd(), i.split('.')[0]),
    )

    nhc_p2s.write_input()
    nhc_p2s.calc()
    nhc_p2s.parse_output()
    nhc_p2s.clean_files()
    print(nhc_p2s.get_percent_free_volume())
```

The following error is shown.

```bash
Traceback (most recent call last):
  File "/Users/andrea/Desktop/SambVca/pocket.py", line 27, in <module>
    nhc_p2s.parse_output()
  File "/Users/andrea/opt/miniconda3/envs/tiro/lib/python3.10/site-packages/py2sambvca/py2sambvca.py", line 225, in parse_output
    "free_volume": float(m1[1]),
TypeError: 'NoneType' object is not subscriptable
```

Scraping a bit in your code, I saw a regex expression to get all the volume values and percenteges. I copy-pasted the output in a regex site and applied the regex to find the volume and it does not find any result.

Messing around with the regex code (but I'm not an expert), I found a match reducing the number of spaces between the values setting a minimum value of 4 as follow and not specifying the maximum: 
`^[ ]{4,}(\d*\.\d*)[ ]{5,}(\d*\.\d*)[ ]{4,}(\d*\.\d*)[ ]{4,}(\d*\.\d*)$`

**Comment by JacksonBurns** [comment]
Hi @andre-cloud thanks for finding this and for the thorough report! Could you upload an example file (either the input file you are putting into `p2s` or the output file generated by `sabmvca21`) so that I can reproduce this error inside a unit test?

**Comment by andre-cloud** [comment]
Sure. Since it's an ongoing research, I censored geometry. I hope you can understand.

[py2sambvca_input.out.zip](https://github.com/JacksonBurns/py2sambvca/files/11028828/py2sambvca_input.out.zip)

**Comment by JacksonBurns** [comment]
@andre-cloud thanks for providing the file! Censoring the geometry is absolutely fine.

I was able to reproduce the error you described. All of my testing up to this point had never produced an output file where the free volume was >=1000 cubic angstrom, so the regex failed (as you discovered). To (hopefully) future-proof this, I have removed the hardcoded counting of the spaces altogether. If anyone comes along with a species with >=10,000 cubic angstrom, it should work for them too (if such a molecule exists).

This issue will be automatically closed when the changes are merged into main. Please feel free to re-open this issue or start another one if the problem persists. Thanks again for finding and reporting this!
